# Generated by Django 4.1.4 on 2022-12-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_invoice_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
