# Generated by Django 4.0.1 on 2022-12-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_invoice_due_date1_alter_invoice_due_date2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='gst_no',
            field=models.CharField(max_length=100),
        ),
    ]
