# Generated by Django 4.0.1 on 2022-12-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_invoice_gst_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='cgst_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
