# Generated by Django 4.0.1 on 2022-12-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_invoice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='description',
            field=models.CharField(choices=[('data_Science', 'Data Science'), ('data_Analysts', 'Data Analysts')], max_length=100),
        ),
    ]
