# Generated by Django 4.0.1 on 2022-12-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_invoice_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='description',
            field=models.CharField(choices=[('Data science', 'Data Science'), ('Data Analysts', 'Data Analysts')], max_length=100),
        ),
    ]
