# Generated by Django 4.0.1 on 2022-12-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_invoice_description2'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='amount2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='amount3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='description3',
            field=models.CharField(blank=True, choices=[('Data science', 'Data Science'), ('Data Analysts', 'Data Analysts')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='quantity2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='quantity3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='unit_price2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='unit_price3',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
