# Generated by Django 4.0.1 on 2022-12-31 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_invoice_amount2_invoice_amount3_invoice_description3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='logo',
            field=models.ImageField(null=True, upload_to='images/logo'),
        ),
    ]
