# Generated by Django 4.0.1 on 2023-01-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_invoice_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('voucher_no', models.IntegerField()),
                ('paid_to', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('amount', models.IntegerField()),
                ('paid_by', models.IntegerField()),
                ('approved_by', models.CharField(max_length=100)),
            ],
        ),
    ]
