# Generated by Django 4.0.1 on 2023-01-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_voucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='paid_by',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
