# Generated by Django 4.0.1 on 2023-01-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_voucher_paid_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='date',
            field=models.DateField(),
        ),
    ]
