# Generated by Django 4.0.1 on 2023-01-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_invoice_gst_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='course_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
