# Generated by Django 4.0.1 on 2023-01-03 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_invoice_total_amount_in_words'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='total_amount_in_words',
            new_name='amount_in_words',
        ),
    ]
