# Generated by Django 4.0.1 on 2023-01-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_rename_total_amount_in_words_invoice_amount_in_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('card', 'card'), ('cash', 'cash')], max_length=100, null=True),
        ),
    ]
