# Generated by Django 4.0.1 on 2023-01-04 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_voucher_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='card_details',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
