# Generated by Django 4.0.1 on 2023-01-04 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_voucher_on_account_of'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='logo',
        ),
    ]
